#ifndef _EEPROM_H_
#define _EEPROM_H_

// EEPROM addresses for the values that are stored in the PIC

#define FIRMWARE_MAJOR_VERSION_ADDRESS  0x00
#define FIRMWARE_MINOR_VERSION_ADDRESS  0x01

#define SERVO1_LOWEST_STATE_ADDRESS     0x02
#define SERVO1_NETRUAL_STATE_ADDRESS    0x03
#define SERVO1_HIGHEST_STATE_ADDRESS    0x04

#define SERVO2_LOWEST_STATE_ADDRESS     0x05
#define SERVO2_NETRUAL_STATE_ADDRESS    0x06
#define SERVO2_HIGHEST_STATE_ADDRESS    0x07

#define SERVO3_LOWEST_STATE_ADDRESS     0x08
#define SERVO3_NETRUAL_STATE_ADDRESS    0x09
#define SERVO3_HIGHEST_STATE_ADDRESS    0x0A

#define SERVO4_LOWEST_STATE_ADDRESS     0x0B
#define SERVO4_NETRUAL_STATE_ADDRESS    0x0C
#define SERVO4_HIGHEST_STATE_ADDRESS    0x0D

#define SERVO5_LOWEST_STATE_ADDRESS     0x0E
#define SERVO5_NETRUAL_STATE_ADDRESS    0x0F
#define SERVO5_HIGHEST_STATE_ADDRESS    0x10

#define SERVO6_LOWEST_STATE_ADDRESS     0x11
#define SERVO6_NETRUAL_STATE_ADDRESS    0x12
#define SERVO6_HIGHEST_STATE_ADDRESS    0x13

#define SERVO7_LOWEST_STATE_ADDRESS     0x14
#define SERVO7_NETRUAL_STATE_ADDRESS    0x15
#define SERVO7_HIGHEST_STATE_ADDRESS    0x16

#define SERVO8_LOWEST_STATE_ADDRESS     0x17
#define SERVO8_NETRUAL_STATE_ADDRESS    0x18
#define SERVO8_HIGHEST_STATE_ADDRESS    0x19

#define SERVO9_LOWEST_STATE_ADDRESS     0x1A
#define SERVO9_NETRUAL_STATE_ADDRESS    0x1B
#define SERVO9_HIGHEST_STATE_ADDRESS    0x1C

#define SERVO10_LOWEST_STATE_ADDRESS    0x1D
#define SERVO10_NETRUAL_STATE_ADDRESS   0x1E
#define SERVO10_HIGHEST_STATE_ADDRESS   0x1F

#define SERVO11_LOWEST_STATE_ADDRESS    0x20
#define SERVO11_NETRUAL_STATE_ADDRESS   0x21
#define SERVO11_HIGHEST_STATE_ADDRESS   0x22

#define SERVO12_LOWEST_STATE_ADDRESS    0x23
#define SERVO12_NETRUAL_STATE_ADDRESS   0x24
#define SERVO12_HIGHEST_STATE_ADDRESS   0x25

#define SERVO13_LOWEST_STATE_ADDRESS    0x26
#define SERVO13_NETRUAL_STATE_ADDRESS   0x27
#define SERVO13_HIGHEST_STATE_ADDRESS   0x28

#define LIGHT1_LOWEST_STATE_ADDRESS     0x29
#define LIGHT1_DEFAULT_STATE_ADDRESS    0x2A
#define LIGHT1_HIGHEST_STATE_ADDRESS    0x2B

#define LIGHT2_LOWEST_STATE_ADDRESS     0x29
#define LIGHT2_DEFAULT_STATE_ADDRESS    0x2A
#define LIGHT2_HIGHEST_STATE_ADDRESS    0x2B

extern void saveSetting(const unsigned char address, const unsigned char value);
extern unsigned char loadSetting(const unsigned char address);

#endif